-- Root: core geometry (dynamic Ω_k) + SO(8) closure (from package HQIVGenerators) + downstream.
import Hqiv.Geometry.OctonionicLightCone
import Hqiv.Geometry.AuxiliaryField
import Hqiv.Geometry.HQVMetric
import Hqiv.Geometry.HQVMetricAnalytic
import Hqiv.Geometry.HQVMPerturbations
import Hqiv.Geometry.HQVMCLASSBridge
import Hqiv.Geometry.Now
import Hqiv.SO8Closure
import Hqiv.Conservations
import Hqiv.Physics.Baryogenesis
import Hqiv.Physics.ModifiedMaxwell
import Hqiv.Physics.SchematicPlasmaCurrent
import Hqiv.Physics.GRFromMaxwell
import Hqiv.Physics.Forces
import Hqiv.Physics.Action
import Hqiv.Physics.CovariantSolution
import Hqiv.Physics.SM_GR_Unification
import Hqiv.Physics.NuclearAndAtomicSpectra
import Hqiv.QuantumMechanics.Schrodinger
import Hqiv.QuantumMechanics.UncertaintyPrinciple
import Hqiv.Algebra.OctonionBasics
import Hqiv.Algebra.G2Embedding
import Hqiv.Algebra.PhaseLiftDelta
import Hqiv.Algebra.SO8ClosureAbstract
import Hqiv.Algebra.Triality
import Hqiv.Algebra.SMEmbedding
import Hqiv.Algebra.AnomalyCancellation
