-- Physics/geometry build: no generator stack (avoids GeneratorsLieClosureData stack overflow).
-- Use: lake build HQIVPhysics
import Hqiv.Geometry.OctonionicLightCone
import Hqiv.Geometry.SphericalHarmonicsBridge
import Hqiv.Geometry.AuxiliaryField
import Hqiv.Geometry.HQVMetric
import Hqiv.Geometry.HQVMetricAnalytic
import Hqiv.Geometry.HQVMPerturbations
import Hqiv.Geometry.HQVMCLASSBridge
import Hqiv.Geometry.HQVMDiscreteLaplacian
import Hqiv.Geometry.HQVMDiscretePoisson
import Hqiv.Geometry.HQVMGlobalLocalDictionary
import Hqiv.Geometry.HQVMConsistency
import Hqiv.Geometry.Now
import Hqiv.Conservations
import Hqiv.Physics.Baryogenesis
import Hqiv.Physics.ModifiedMaxwell
import Hqiv.Physics.SchematicPlasmaCurrent
import Hqiv.Physics.GRFromMaxwell
import Hqiv.Physics.Forces
import Hqiv.Physics.BoundStates
import Hqiv.Physics.DerivedGaugeAndLeptonSector
import Hqiv.Physics.NuclearAndAtomicSpectra
import Hqiv.Physics.HQIVNuclei
import Hqiv.Physics.HQIVAtoms
import Hqiv.Physics.HQIVMolecules
import Hqiv.Physics.HQIVLongRange
import Hqiv.Physics.HQIVAssembly
import Hqiv.Physics.HQIVCollectiveModes
import Hqiv.QuantumMechanics.Schrodinger
import Hqiv.QuantumMechanics.UncertaintyPrinciple
import Hqiv.QuantumOptics.HorizonQED
