import Mathlib.Data.Real.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.LinearAlgebra.Matrix.Defs
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.LinearAlgebra.LinearIndependent.Basic

-- OctonionicLightCone: counting over O (latticeSimplexCount, curvature 6⁷√3); doc only.
import Hqiv.Generators
import Hqiv.OctonionLeftMultiplication

namespace Hqiv

/-!
# Generators from first assumptions — working backward

We **prove** that the 28 so(8) generators (defined in `Generators.lean` from
`matrices.py` output) **arise from** the first assumptions of the framework.

## First assumptions (in order)

1. **Counting over O (OctonionicLightCone):**
   - Discrete null lattice: stars-and-bars count `latticeSimplexCount m = (m+2)(m+1)`.
   - **Octonion dimension 8** (1 real + 7 imaginary): new modes = 8 × lattice count;
     curvature norm uses 6⁷√3 (cube directions^octonion_dim × half-diagonal).
   - So the **algebraic dimension 8** is fixed by the light-cone counting.

2. **Octonion algebra on ℝ⁸:**
   - The algebra O = ℝ⁸ has a multiplication given by the **Fano plane** (7 imaginary
     units e₁,…,e₇). Left multiplication by e_i is a linear map ℝ⁸ → ℝ⁸, hence an
     8×8 real matrix **L(e_i)**. The paper and `HQVM/matrices.py` fix a specific
     choice (L(e₇) = colour-preferred axis).

3. **Phase-lift generator Δ:**
   - The time angle δθ′ (from HQVMetric) couples to a rotation in the (e₁, e₇) plane.
   - **Δ** is the generator of that rotation: antisymmetric 8×8 with Δ₁₇ = -1,
     Δ₇₁ = 1 (indexing 0..7), all other entries 0. Defined explicitly below.

4. **Lie closure:**
   - **g₂** = the Lie algebra (under matrix commutator [A,B] = A*B - B*A) generated
     by the 14 commutators [L(e_i), L(e_j)] for i < j (derivations of O).
   - The Lie algebra generated by **g₂ ∪ {Δ}** closes to full **so(8)** (dimension 28).
   - Authoritative construction: `HQVM/matrices.py` (`OctonionHQIVAlgebra`,
     `lie_closure_basis`).

## Goal (theorem we work toward)

**The 28 matrices `so8Generator 0`, …, `so8Generator 27` are a basis for the Lie
algebra generated by g₂ and Δ.** So they “come from” the first assumptions:
octonion dimension 8 → L(e_i), Δ → Lie closure → our 28 generators.

Proof path (to be filled):
- Define L(e_1), …, L(e_7) and Δ in Lean (from matrices.py or from Fano axioms).
- Show each lies in the span of antisymmetric 8×8 matrices; [L_i,L_j] and Δ in the span.
- Show the Lie closure of g₂ ∪ {Δ} has dimension 28.
- Show the 28 so8Generators are antisymmetric, linearly independent, and span the
  same space as that closure (hence they are a basis for it).
-/

/-- **Lie bracket** of 8×8 real matrices: [A, B] = A * B - B * A.
The algebra generated by a set S is the smallest Lie subalgebra containing S. -/
def lieBracket (A B : Matrix (Fin 8) (Fin 8) ℝ) : Matrix (Fin 8) (Fin 8) ℝ :=
  A * B - B * A

/-- **Phase-lift generator Δ**: rotation in the (e₁, e₇) plane.
In 0-based indexing: row 1, col 7 = -1; row 7, col 1 = 1; else 0.
Matches `HQVM/matrices.py` `_build_Delta()`. -/
def phaseLiftDelta : Matrix (Fin 8) (Fin 8) ℝ :=
  Matrix.of (fun i j => if (i = 1 ∧ j = 7) then (-1 : ℝ)
    else if (i = 7 ∧ j = 1) then (1 : ℝ) else 0)

lemma phaseLiftDelta_17 : phaseLiftDelta 1 7 = (-1 : ℝ) := by
  simp [phaseLiftDelta, Matrix.of_apply]

lemma phaseLiftDelta_71 : phaseLiftDelta 7 1 = (1 : ℝ) := by
  simp [phaseLiftDelta, Matrix.of_apply]

lemma phaseLiftDelta_antisymm (i j : Fin 8) :
    phaseLiftDelta i j + phaseLiftDelta j i = 0 := by
  fin_cases i <;> fin_cases j <;> simp [phaseLiftDelta, Matrix.of_apply]

/-- **Octonion (imaginary) dimension** — number of imaginary units. Used in
OctonionicLightCone (curvature norm 6^7 √3) and here as the number of L(e_i). -/
def octonionImaginaryCount : ℕ := 7

/-- **g₂ dimension** — number of independent commutators [L(e_i), L(e_j)], i < j. -/
def g2Dim : ℕ := 14

/-- **Dimension of the Lie closure** (g₂ + Δ → so(8)). Must equal `so8GeneratorCount`. -/
def lieClosureDim : ℕ := 28

theorem lieClosureDim_eq_so8GeneratorCount :
    lieClosureDim = so8GeneratorCount := rfl

/-!
## Main theorem statement (to be proved)

We state the goal: the 28 generators we defined form a basis for the Lie algebra
that arises from the first assumptions (L(e_i), Δ, closure).

**Step 1 (antisymmetry):** ~~Prove~~ **Proved** in `Generators.lean`: `so8Generator_antisymm` —
each `so8Generator k` satisfies `so8Generator k + (so8Generator k)ᵀ = 0`.

**Step 2 (generators in closure):** There exist 7 matrices L₁,…,L₇ (left multiplication
by imaginary octonion units) and Δ = `phaseLiftDelta` such that the Lie algebra
generated by { [L_i, L_j] | i < j } ∪ {Δ} has dimension 28 and its span equals
the span of { so8Generator 0, …, so8Generator 27 }.

**Step 3 (basis):** The 28 so8Generators are linearly independent, hence a basis
for that closure. So they **come from** the first assumptions.
-/

/-- **g₂ basis:** the 14 commutators [L(e_i), L(e_j)] for i < j (lex order).
Matches `HQVM/matrices.py` `_build_g2_basis()` (first 14 of the 21 pairs). -/
def g2_comm_12 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_1 octonionLeftMul_2
def g2_comm_13 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_1 octonionLeftMul_3
def g2_comm_14 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_1 octonionLeftMul_4
def g2_comm_15 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_1 octonionLeftMul_5
def g2_comm_16 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_1 octonionLeftMul_6
def g2_comm_17 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_1 octonionLeftMul_7
def g2_comm_23 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_2 octonionLeftMul_3
def g2_comm_24 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_2 octonionLeftMul_4
def g2_comm_25 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_2 octonionLeftMul_5
def g2_comm_26 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_2 octonionLeftMul_6
def g2_comm_27 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_2 octonionLeftMul_7
def g2_comm_34 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_3 octonionLeftMul_4
def g2_comm_35 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_3 octonionLeftMul_5
def g2_comm_36 : Matrix (Fin 8) (Fin 8) ℝ := lieBracket octonionLeftMul_3 octonionLeftMul_6

/-- **Target (proved in GeneratorsLieClosure):** Every [so8Generator i, so8Generator j]
lies in the span of the 28 generators. So the 28 form a Lie subalgebra. -/
def generators_lie_closed : Prop :=
  ∀ i j : Fin 28, ∃ f : Fin 28 → ℝ,
    lieBracket (so8Generator i) (so8Generator j) = ∑ k, f k • so8Generator k

/-- **Generators from octonion closure:** The 28 so(8) generators are antisymmetric
(Generators.so8Generator_antisymm), closed under Lie bracket (GeneratorsLieClosure.lieBracket_in_span),
and linearly independent (GeneratorsLieClosure.so8_generators_linear_independent).
So they form a basis for so(8). Proved in `GeneratorsLieClosure.generators_from_octonion_closure`. -/
def generators_from_octonion_closure : Prop :=
  (∀ k : Fin 28, so8Generator k + Matrix.transpose (so8Generator k) = 0) ∧
  generators_lie_closed ∧
  LinearIndependent ℝ (fun k : Fin 28 => so8Generator k)

/-!
## Status

1. ~~Export L(e_1)..L(e_7)~~ **Done:** `Hqiv.OctonionLeftMultiplication`.
2. ~~**Define g₂**~~ **Done:** `g2_comm_12` … `g2_comm_36`.
3. ~~**Lie bracket closure**~~ **Done:** `lieBracket_in_span` in `GeneratorsLieClosure`.
4. ~~**Antisymmetry**~~ **Done:** `so8Generator_antisymm` in `Generators.lean`.
5. **Linear independence** — `so8_generators_linear_independent` in GeneratorsLieClosure
   (depends on `so8CoordMatrix_det_ne_zero`; det = -1 via script).
6. **Combined theorem** — `generators_from_octonion_closure` in GeneratorsLieClosure.
-/

end Hqiv
