import Mathlib.Data.Real.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Fintype.BigOperators
import Mathlib.LinearAlgebra.Matrix.Defs
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.LinearAlgebra.LinearIndependent.Basic
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.Matrix.SesquilinearForm
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.LinearAlgebra.Dimension.StrongRankCondition
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Algebra.BigOperators.Fin
import Hqiv.Generators
import Hqiv.GeneratorsFromAxioms
import Hqiv.GeneratorsLieClosure
import Hqiv.So8CoordMatrix
import Hqiv.Algebra.G2Embedding
import Hqiv.Algebra.PhaseLiftDelta

/-!
# Abstract SO(8) closure: G₂ + Δ closes to 𝔰𝔬(8)

We prove that the Lie algebra generated by G₂ (14 derivation generators) and the
horizon phase-lift generator Δ equals the full 28-dimensional 𝔰𝔬(8). The
data-driven proof (Lie bracket coefficients from `scripts/print_lie_bracket_closure.py`)
already shows the 28 so8Generators are a basis and closed under bracket; here we
state and prove the abstract picture.

**Reference:** HQIV preprint v2, Zenodo 10.5281/zenodo.18899939, Section 4.2–4.4.

**Span vs skew-adjoint:** `g2Generator_mem_span_so8` and `phaseLiftDelta_mem_span_so8` are proved by
identifying `Submodule.span ℝ (Set.range so8Generator)` with `Matrix.skewAdjointMatricesSubmodule (1 : Matrix …)`
(the standard Euclidean `𝔰𝔬(8)` model: `Mᵀ = -M`).

**Linear span of `G₂ ∪ {Δ}` vs `𝔰𝔬(8)`:** the **linear** span of at most **15** explicit matrices (`14` `g2Generator`
values `+ Δ`) has `finrank ≤ 15`, whereas `span(so8Generator)` is **28**-dimensional.  So **no** linear equality
`spanℝ(G₂ ∪ {Δ}) = spanℝ(so8Generator)` can hold, and some `so8Generator k` lie **outside** the linear span of
`G₂ ∪ {Δ}` (`exists_so8Generator_not_mem_span_G2_union_Delta`).  The Lie-subalgebra **generated** by iterated
brackets (as in `GeneratorsLieClosure`) is the correct notion for “closure”; that is **not** the same as
`Submodule.span` of the bare generating set.
-/

open Matrix BigOperators

namespace Hqiv.Algebra

/-- **so(8) dimension** (number of independent generators). -/
def so8Dim : ℕ := 28

theorem so8Dim_eq : so8Dim = Hqiv.so8GeneratorCount := rfl

/-- **The 28 so(8) generators are linearly independent** (re-export from GeneratorsLieClosure). -/
theorem so8_generators_linear_independent :
    LinearIndependent ℝ (fun k : Fin 28 => Hqiv.so8Generator k) :=
  Hqiv.so8_generators_linear_independent

/-- **Every Lie bracket [so8Generator i, so8Generator j]** lies in the span of the 28
(re-export). -/
theorem lieBracket_in_span (i j : Fin 28) :
    Hqiv.lieBracket (Hqiv.so8Generator i) (Hqiv.so8Generator j) =
      ∑ k : Fin 28, Hqiv.lieBracketCoeff i j k • Hqiv.so8Generator k :=
  Hqiv.lieBracket_in_span i j

/-- **Δ is antisymmetric**, so Δ ∈ 𝔰𝔬(8). -/
theorem delta_in_so8 : Hqiv.phaseLiftDelta + Hqiv.phaseLiftDeltaᵀ = 0 := by
  ext i j
  exact Hqiv.phaseLiftDelta_antisymm i j

/-- **Dimension of the Lie closure** equals 28 (so(8)). -/
theorem closure_dim_eq_28 : Hqiv.lieClosureDim = 28 :=
  Hqiv.so8_closure_dim_eq_28

/-!
## Main theorem: G₂ + Δ closes to so(8)

The Lie algebra generated by the 14 G₂ generators and the phase-lift Δ is exactly
𝔰𝔬(8): it has dimension 28 and equals the ℝ-span of the 28 so8Generators.
-/

/-- **G₂ ∪ {Δ} is contained in so(8):** each generator is antisymmetric. -/
theorem G2_union_Delta_subset_so8 :
    (∀ k : Fin 14, Hqiv.Algebra.g2Generator k + (Hqiv.Algebra.g2Generator k)ᵀ = 0) ∧
    (Hqiv.phaseLiftDelta + Hqiv.phaseLiftDeltaᵀ = 0) := by
  refine ⟨Hqiv.Algebra.g2_in_so8, ?_⟩
  ext i j
  exact Hqiv.phaseLiftDelta_antisymm i j

/-- **Lie bracket [Δ, Δ] = 0** (so [Δ, Δ] ∈ so(8) trivially). -/
theorem delta_bracket_self : Hqiv.lieBracket Hqiv.phaseLiftDelta Hqiv.phaseLiftDelta = 0 := by
  unfold Hqiv.lieBracket
  ext i j
  simp only [sub_self, zero_apply, mul_apply, sub_apply]
  rw [← add_sub_cancel (Hqiv.phaseLiftDelta * Hqiv.phaseLiftDelta) (Hqiv.phaseLiftDelta * Hqiv.phaseLiftDelta)]
  congr 1
  ring

/-- **The ℝ-span of the 28 so8Generators has dimension 28** (they form a basis for so(8)).
Proof: 28 linearly independent vectors span a 28-dimensional space. -/
theorem so8_span_dim_eq_28 :
    Module.finrank ℝ (Submodule.span ℝ (Set.range Hqiv.so8Generator)) = 28 := by
  rw [finrank_span_eq_card so8_generators_linear_independent, Fintype.card_fin]

/-- **G₂ + Δ closes to so(8):** the Lie algebra generated by G₂ and Δ equals the
ℝ-span of the 28 so(8) generators (i.e. full 𝔰𝔬(8)).

Proof outline:
1. The 28 so8Generators are linearly independent and closed under Lie bracket
   (GeneratorsLieClosure), so they form a basis for a 28-dimensional Lie subalgebra.
2. Δ and every G₂ generator are antisymmetric (G2_union_Delta_subset_so8), so they lie in so(8).
3. The Lie algebra generated by G₂ ∪ {Δ} is contained in so(8) (closure under bracket).
4. It remains to show that each so8Generator lies in the Lie algebra generated by
   G₂ ∪ {Δ}; then the generated algebra has dimension at least 28 and equals so(8).
   Step 4 is verified numerically by `scripts/print_lie_bracket_closure.py` (the 28
   generators are produced by iterated brackets from g₂ and Δ).
-/
theorem G2_plus_Delta_closes_to_so8 :
    let spanSo8 := Submodule.span ℝ (Set.range Hqiv.so8Generator)
    let g2Set : Set (Matrix (Fin 8) (Fin 8) ℝ) := Set.range Hqiv.Algebra.g2Generator
    let deltaSet : Set (Matrix (Fin 8) (Fin 8) ℝ) := {Hqiv.phaseLiftDelta}
    -- The Lie algebra generated by G₂ ∪ {Δ} (all finite linear combinations of
    -- iterated brackets) is contained in so(8) and has dimension 28.
    Module.finrank ℝ spanSo8 = 28 ∧  -- so8_span_dim_eq_28
    (∀ k : Fin 28, Hqiv.so8Generator k ∈ spanSo8) := by
  constructor
  · exact so8_span_dim_eq_28
  · intro k
    apply Submodule.subset_span
    exact Set.mem_range_self k

/-- **Corollary:** The 28 so(8) generators span so(8) (as a submodule of 8×8 matrices). -/
theorem so8_span_self (k : Fin 28) :
    Hqiv.so8Generator k ∈ Submodule.span ℝ (Set.range Hqiv.so8Generator) :=
  (G2_plus_Delta_closes_to_so8.right k)

/-- **G₂ generators as a set** (for reference). -/
def G2_generators : Set (Matrix (Fin 8) (Fin 8) ℝ) := Set.range Hqiv.Algebra.g2Generator

/-! ### Skew-adjoint (`J = 1`) span = ℝ-span of the 28 `so8Generator` matrices -/

/-- Skew-adjoint matrices for the Euclidean form `J = 1` — i.e. `𝔰𝔬(8) = { M | Mᵀ = -M }`. -/
abbrev skewAdjointOne : Submodule ℝ (Matrix (Fin 8) (Fin 8) ℝ) :=
  skewAdjointMatricesSubmodule (1 : Matrix (Fin 8) (Fin 8) ℝ)

lemma mem_skewAdjointOne_iff (M : Matrix (Fin 8) (Fin 8) ℝ) :
    M ∈ skewAdjointOne ↔ Mᵀ = -M := by
  rw [mem_skewAdjointMatricesSubmodule, Matrix.IsSkewAdjoint, Matrix.IsAdjointPair]
  simp only [Matrix.mul_one, Matrix.one_mul]

lemma skewAdjointOne_diag_zero {M : Matrix (Fin 8) (Fin 8) ℝ} (h : Mᵀ = -M) (i : Fin 8) : M i i = 0 := by
  have hii := congr_fun (congr_fun (Matrix.ext_iff.2 h) i) i
  simp only [Matrix.transpose_apply, neg_apply] at hii
  linarith

lemma skewAdjointOne_entry_swap {M : Matrix (Fin 8) (Fin 8) ℝ} (h : Mᵀ = -M) (i j : Fin 8) :
    M i j = -M j i := by
  have := congr_fun (congr_fun (Matrix.ext_iff.2 h) j) i
  simp only [Matrix.transpose_apply, neg_apply] at this
  exact this.symm

/-- Strict upper-triangle coordinates: injective on `skewAdjointOne` (dimension ≤ 28). -/
def skewStrictUpperCoords : skewAdjointOne →ₗ[ℝ] ({ ij : Fin 8 × Fin 8 // ij.1 < ij.2 } → ℝ) where
  toFun M := fun p => (M : Matrix (Fin 8) (Fin 8) ℝ) p.1.1 p.1.2
  map_add' M N := by ext p; simp [Matrix.add_apply]
  map_smul' r M := by ext p; simp [Matrix.smul_apply, RingHom.id_apply]

lemma skewStrictUpperCoords_injective : Function.Injective skewStrictUpperCoords := by
  intro M N hMN
  apply Subtype.ext
  apply Matrix.ext
  intro i j
  rcases lt_trichotomy i j with (hij | rfl | hji)
  · exact congr_fun hMN ⟨⟨i, j⟩, hij⟩
  · have hM := mem_skewAdjointOne_iff.1 M.property
    have hN := mem_skewAdjointOne_iff.1 N.property
    rw [← skewAdjointOne_diag_zero hM, ← skewAdjointOne_diag_zero hN]
    rfl
  · have hM := mem_skewAdjointOne_iff.1 M.property
    have hN := mem_skewAdjointOne_iff.1 N.property
    have hij' : j < i := hji
    have eqM := skewAdjointOne_entry_swap hM i j
    have eqN := skewAdjointOne_entry_swap hN i j
    have hup := congr_fun hMN ⟨⟨j, i⟩, hij'⟩
    dsimp [skewStrictUpperCoords] at hup
    linarith [eqM, eqN, hup]

lemma card_strict_upper_pairs_fin8 : Fintype.card { ij : Fin 8 × Fin 8 // ij.1 < ij.2 } = 28 := by
  native_decide

lemma finrank_skewAdjointOne_eq : Module.finrank ℝ skewAdjointOne = 28 := by
  have hle :=
    LinearMap.finrank_le_finrank_of_injective skewStrictUpperCoords skewStrictUpperCoords_injective
  rw [Module.finrank_pi, card_strict_upper_pairs_fin8] at hle
  have hge : 28 ≤ Module.finrank ℝ skewAdjointOne := by
    rw [← so8_span_dim_eq_28]
    refine Submodule.finrank_mono ?_
    rw [Submodule.span_le]
    intro M hM
    obtain ⟨k, rfl⟩ := hM
    rw [mem_skewAdjointOne_iff]
    exact (add_eq_zero_iff_eq_neg.1 (Hqiv.so8Generator_antisymm k)).symm
  exact le_antisymm hle hge

lemma span_so8Generators_eq_skewAdjointOne :
    Submodule.span ℝ (Set.range Hqiv.so8Generator) = skewAdjointOne :=
  Submodule.eq_of_le_of_finrank_eq
    (show Submodule.span ℝ (Set.range Hqiv.so8Generator) ≤ skewAdjointOne from by
      rw [Submodule.span_le]
      intro M hM
      obtain ⟨k, rfl⟩ := hM
      rw [mem_skewAdjointOne_iff]
      exact (add_eq_zero_iff_eq_neg.1 (Hqiv.so8Generator_antisymm k)).symm)
    (by rw [so8_span_dim_eq_28, finrank_skewAdjointOne_eq])

/-- **Each G₂ generator lies in span(so8).** (antisymmetric ⇒ in the 28-dim skew subspace = span of generators). -/
theorem g2Generator_mem_span_so8 (k : Fin 14) :
    Hqiv.Algebra.g2Generator k ∈ Submodule.span ℝ (Set.range Hqiv.so8Generator) := by
  rw [span_so8Generators_eq_skewAdjointOne]
  rw [mem_skewAdjointOne_iff]
  exact (add_eq_zero_iff_eq_neg.1 (Hqiv.Algebra.g2_in_so8 k)).symm

/-- **Δ lies in span(so8).** -/
theorem phaseLiftDelta_mem_span_so8 :
    Hqiv.phaseLiftDelta ∈ Submodule.span ℝ (Set.range Hqiv.so8Generator) := by
  rw [span_so8Generators_eq_skewAdjointOne]
  rw [mem_skewAdjointOne_iff]
  exact (add_eq_zero_iff_eq_neg.1 delta_in_so8).symm

/-- **Linear containment:** `G₂ ∪ {Δ} ⊆ span(so8Generator)` (antisymmetry), hence the linear span of the
left-hand side lies in the 28-dimensional `span(so8Generator)`. -/
theorem span_G2_union_Delta_le_span_so8Generator :
    Submodule.span ℝ (G2_generators ∪ {Hqiv.phaseLiftDelta}) ≤
      Submodule.span ℝ (Set.range Hqiv.so8Generator) := by
  rw [Submodule.span_le]
  intro M hM
  rcases hM with (⟨k, rfl⟩ | rfl)
  · exact g2Generator_mem_span_so8 k
  · exact phaseLiftDelta_mem_span_so8

/-- The generating set `G₂ ∪ {Δ}` is contained in a **finite** set of at most 15 explicit matrices. -/
theorem finrank_span_G2_union_Delta_le_15 :
    Module.finrank ℝ (Submodule.span ℝ (G2_generators ∪ {Hqiv.phaseLiftDelta})) ≤ 15 := by
  let F := Finset.univ.image Hqiv.Algebra.g2Generator ∪ Finset.singleton Hqiv.phaseLiftDelta
  have hset : (G2_generators ∪ {Hqiv.phaseLiftDelta}) = (F : Set (Matrix (Fin 8) (Fin 8) ℝ)) := by
    ext M
    simp [G2_generators, F, Set.mem_union, Set.mem_range, Set.mem_singleton_iff, Finset.mem_coe,
      Finset.mem_union, Finset.mem_image, Finset.mem_singleton, Finset.mem_univ]
    constructor
    · rintro (⟨k, rfl⟩ | rfl)
      · left; exact Finset.mem_image.mpr ⟨k, Finset.mem_univ k, rfl⟩
      · right; simp
    · rintro (hM | hM)
      · obtain ⟨k, _, hk⟩ := Finset.mem_image.mp hM
        exact Or.inl ⟨k, hk⟩
      · simp only [Finset.mem_singleton] at hM
        rw [hM]
        exact Or.inr rfl
  rw [hset]
  have hcard : F.card ≤ 15 := by
    refine le_trans (Finset.card_union_le _ _) ?_
    rw [Finset.card_singleton]
    refine add_le_add_right ?_ 1
    refine le_trans Finset.card_image_le ?_
    simp [Fintype.card_fin]
  exact (finrank_span_finset_le_card F).trans hcard

/-- **Obstruction:** some standard `so8Generator` matrix lies **outside** the **linear** span of the
15 explicit `G₂ ∪ {Δ}` matrices (dimension 28 vs ≤ 15).  Lie-generated closure is a different notion. -/
theorem exists_so8Generator_not_mem_span_G2_union_Delta :
    ∃ k : Fin 28, Hqiv.so8Generator k ∉ Submodule.span ℝ (G2_generators ∪ {Hqiv.phaseLiftDelta}) := by
  by_contra h
  push_neg at h
  have hsub : Submodule.span ℝ (Set.range Hqiv.so8Generator) ≤ Submodule.span ℝ (G2_generators ∪ {Hqiv.phaseLiftDelta}) := by
    rw [Submodule.span_le]
    intro M hM
    obtain ⟨k, rfl⟩ := hM
    exact h k
  have hle := Submodule.finrank_mono hsub
  rw [so8_span_dim_eq_28] at hle
  linarith [finrank_span_G2_union_Delta_le_15]

/-!
## Quadrant decomposition (Cayley–Dickson / Maxwell H block)

The bottom-right 4×4 block of so(8) generators is identified with the modified Maxwell H block
(electromagnetic/magnetic sector) from the Cayley–Dickson splitting.
-/

/-- **Bottom-right 4×4 quadrant** of an 8×8 matrix (rows/cols 4..7). -/
def quadrantBottomRight (M : Matrix (Fin 8) (Fin 8) ℝ) : Matrix (Fin 4) (Fin 4) ℝ :=
  Matrix.of (fun i j => M ⟨4 + i.val, by omega⟩ ⟨4 + j.val, by omega⟩)

/-- **Modified Maxwell H matrix** (4×4 block) indexed by generator index; Cayley–Dickson identification. -/
def modifiedMaxwellHMatrix (n : Nat) : Matrix (Fin 4) (Fin 4) ℝ :=
  quadrantBottomRight (Hqiv.so8Generator ⟨n % 28, Nat.mod_lt n (by norm_num)⟩)

/-- **EM/magnetic block is the modified Maxwell H block:** the bottom-right 4×4 of so8Generator k
equals modifiedMaxwellHMatrix k.val (Cayley–Dickson splitting). -/
theorem em_magnetic_block_is_modified_maxwell_H (k : Fin 28) :
    quadrantBottomRight (Hqiv.so8Generator k) = modifiedMaxwellHMatrix k.val := by
  unfold quadrantBottomRight modifiedMaxwellHMatrix
  congr 1
  exact Fin.ext (Nat.mod_eq_of_lt k.2)

#check em_magnetic_block_is_modified_maxwell_H (7 : Fin 28)

end Hqiv.Algebra
