import Mathlib.Data.Finset.Basic
import Hqiv.QuantumMechanics.HorizonFreeFieldScaffold

/-!
# Local algebra net (minimal Haag–Kastler–style scaffold)

A **causal region** is modelled as a finite subset of the four Minkowski coordinate indices
(`Finset (Fin 4)` — same chart as `SpacetimeChart` in `ContinuumManyBodyQFTScaffold`).

To each region we assign the **same** abelian diagonal algebra generated by `smearedField w`
(`HorizonFreeFieldScaffold`).  This is the honest **trivial** net: isotony holds trivially, and
**Einstein causality** (commuting observables in spacelike-separated regions) follows from
`smearedField_opCommutator_eq_zero` without any geometric input — the content is *structural*.

A nontrivial net would restrict supports to regions (via weights vanishing outside `R`) and would
pair with spacelike separation in `ContinuumManyBodyQFTScaffold` — see `PatchQFTBridge`
(`WeightSupportInRegion`, `patchAlgebraAt`, `patchChartPoint`).  Exact CCR as literal fixed-size
matrices is ruled out (`CCRFiniteDimObstruction`); HQIV instead uses **finite patches** and **limits**
along the light-cone / shell ladder rather than a global infinite-dimensional carrier.
-/

namespace Hqiv.QM

open scoped InnerProductSpace

noncomputable section

/-- Open / bounded region in the fixed `Fin 4` chart (scaffold). -/
abbrev SpacetimeRegion := Finset (Fin 4)

/-- Map regions to sets of bounded operators on `LatticeHilbert n`. -/
structure LocalOperatorNet (n : ℕ) where
  algebraAt : SpacetimeRegion → Set (LatticeHilbert n →ₗ[ℂ] LatticeHilbert n)

/-- **Constant** diagonal net: every region gets the full family of smeared diagonal operators. -/
noncomputable def diagonalSmearedNet (n : ℕ) : LocalOperatorNet n where
  algebraAt := fun _ => Set.range (fun w : Fin n → ℝ => smearedField w)

theorem diagonalSmearedNet_algebraAt_eq (n : ℕ) (R S : SpacetimeRegion) :
    (diagonalSmearedNet n).algebraAt R = (diagonalSmearedNet n).algebraAt S :=
  rfl

/-- Isotony: larger region contains at least as many observables (here: equality, so trivial). -/
theorem diagonalSmearedNet_isotony (n : ℕ) (R S : SpacetimeRegion) (_h : R ⊆ S) :
    (diagonalSmearedNet n).algebraAt R ⊆ (diagonalSmearedNet n).algebraAt S := by
  rw [diagonalSmearedNet_algebraAt_eq n R S]

/--
Einstein / microcausality at the **operator** level: observables in any two regions commute
(here because the assigned algebra is abelian).
-/
theorem diagonalSmearedNet_commute_all_regions (n : ℕ) (R S : SpacetimeRegion)
    (A B : LatticeHilbert n →ₗ[ℂ] LatticeHilbert n)
    (hA : A ∈ (diagonalSmearedNet n).algebraAt R) (hB : B ∈ (diagonalSmearedNet n).algebraAt S) :
    opCommutator A B = 0 := by
  rcases hA with ⟨w, rfl⟩
  rcases hB with ⟨v, rfl⟩
  exact smearedField_opCommutator_eq_zero w v

end

end Hqiv.QM
