#!/usr/bin/env python3
"""
Compute the 28×28 matrix of upper-triangle coordinates of the so(8) generators
and its determinant. Used to prove linear independence in Lean.

Run: cd ~/Repos/HQIV_LEAN && PYTHONPATH=~/Repos/HQIV python3 scripts/print_linear_independence.py [--write]

Output: determinant value and (with --write) writes Hqiv/So8CoordMatrix.lean
with the matrix def so the det can be proved nonzero in Lean.
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO_LEAN = Path(__file__).resolve().parent.parent
_REPO_HQIV = _REPO_LEAN.parent / "HQIV"
if _REPO_HQIV.exists():
    sys.path.insert(0, str(_REPO_HQIV))


def upper_triangle_pairs() -> list[tuple[int, int]]:
    """Lex order: (0,1),(0,2),...,(0,7),(1,2),...,(6,7)."""
    out = []
    for i in range(8):
        for j in range(i + 1, 8):
            out.append((i, j))
    assert len(out) == 28
    return out


def matrix_to_vec28(M) -> list[float]:
    """Flatten 8×8 matrix to 28-dim (upper triangle, row < col)."""
    pairs = upper_triangle_pairs()
    return [float(M[i][j]) for (i, j) in pairs]


def to_lean_real(x: float) -> str:
    if abs(x) < 1e-12:
        return "(0 : ℝ)"
    if abs(x - 1) < 1e-12:
        return "(1 : ℝ)"
    if abs(x + 1) < 1e-12:
        return "(-1 : ℝ)"
    return f"({x:.14g} : ℝ)"


def main() -> None:
    import numpy as np
    from HQVM.matrices import OctonionHQIVAlgebra

    alg = OctonionHQIVAlgebra(verbose=False)
    basis = alg.lie_closure_basis(tol=1e-10)
    assert len(basis) == 28
    # B[p,k] = (generator k) at upper-triangle position p
    pairs = upper_triangle_pairs()
    B = np.array([[basis[k][i][j] for k in range(28)] for (i, j) in pairs])
    assert B.shape == (28, 28)
    det_B = np.linalg.det(B)
    print(f"det(so8CoordMatrix) = {det_B}", file=sys.stderr)
    print(f"det != 0: {abs(det_B) > 1e-6}", file=sys.stderr)

    if "--write" in sys.argv or "-w" in sys.argv:
        out_path = _REPO_LEAN / "Hqiv" / "So8CoordMatrix.lean"
        with open(out_path, "w") as f:
            f.write("import Hqiv.Generators\n\n")
            f.write("namespace Hqiv\n\n")
            f.write("/-- 28×28 matrix of upper-triangle coordinates: so8CoordMatrix p k = (so8Generator k) at p-th (i,j) with i<j.\n")
            f.write("Lex order (0,1)..(0,7),(1,2)..(6,7). Generated by scripts/print_linear_independence.py -/\n")
            f.write("def so8CoordMatrix : Matrix (Fin 28) (Fin 28) ℝ := Matrix.of (fun p k =>\n")
            f.write("  match p, k with\n")
            for p in range(28):
                i, j = pairs[p]
                for k in range(28):
                    val = float(B[p, k])
                    f.write(f"  | {p}, {k} => {to_lean_real(val)}\n")
            f.write("  end)\n\n")
            f.write("end Hqiv\n")
        print(f"Wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
