#!/usr/bin/env python3
"""
Compute Lie bracket closure: [gen_i, gen_j] as linear combination of the 28 generators.
Outputs Lean 4 def so we can prove lieBracket (so8Generator i) (so8Generator j)
lies in the span of the 28 for all i, j.

Run: cd ~/Repos/HQIV_LEAN && PYTHONPATH=~/Repos/HQIV python3 scripts/print_lie_bracket_closure.py

Output: append to Hqiv/GeneratorsLieClosure.lean (or paste the def + theorem).
Antisymmetric 8×8 matrices have 28 DOF (upper triangle). We build the 28×28 matrix B
of generator columns, solve B c = v for each bracket vector v.
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO_LEAN = Path(__file__).resolve().parent.parent
_REPO_HQIV = _REPO_LEAN.parent / "HQIV"
if _REPO_HQIV.exists():
    sys.path.insert(0, str(_REPO_HQIV))

TOL = 1e-10  # zero threshold for coefficients


def matrix_to_vec28(M) -> list[float]:
    """Flatten 8×8 matrix to 28-dim (upper triangle, row < col)."""
    out = []
    for i in range(8):
        for j in range(i + 1, 8):
            out.append(float(M[i][j]))
    return out


def to_lean_real(x: float) -> str:
    if abs(x) < TOL:
        return "(0 : ℝ)"
    if abs(x - 1) < TOL:
        return "(1 : ℝ)"
    if abs(x + 1) < TOL:
        return "(-1 : ℝ)"
    return f"({x:.14g} : ℝ)"


def write_lean_file(out_path: Path, coeff: list) -> None:
    """Write full Lean 4 file with lieBracketCoeff def (single giant match; can overflow stack)."""
    with open(out_path, "w") as f:
        f.write("import Hqiv.Generators\n\n")
        f.write("namespace Hqiv\n\n")
        f.write("/-- Coefficients for [so8Generator i, so8Generator j] = ∑ k, lieBracketCoeff i j k • so8Generator k.\n")
        f.write("Generated by scripts/print_lie_bracket_closure.py -/\n")
        f.write("def lieBracketCoeff (i j : Fin 28) : Fin 28 → ℝ := fun k =>\n")
        f.write("  match i, j, k with\n")
        for i in range(28):
            for j in range(28):
                c = coeff[i][j]
                for k in range(28):
                    val = to_lean_real(c[k])
                    f.write(f"  | {i}, {j}, {k} => {val}\n")
        f.write("  end\n\n")
        f.write("end Hqiv\n")


def write_lean_chunked(repo_lean: Path, coeff: list) -> None:
    """Write chunked Lean 4 files: one module per i (GeneratorsLieClosureData0..27), each with
    a nested match on j then k, plus main GeneratorsLieClosureData.lean that dispatches on i.
    Avoids one 21k-case term that overflows the stack."""
    hqiv = repo_lean / "Hqiv"
    hqiv.mkdir(parents=True, exist_ok=True)

    for i in range(28):
        path = hqiv / f"GeneratorsLieClosureData{i}.lean"
        with open(path, "w") as f:
            f.write("import Hqiv.Generators\n\n")
            f.write(f"/-- Row i = {i} of lieBracketCoeff (j,k) ↦ coefficient. Chunked to avoid stack overflow. -/\n")
            # Use array lookup to avoid large match/end; no namespace so each module has its own lieBracketCoeffRow.
            f.write("private def rowData : Array ℝ := #[\n")
            for j in range(28):
                c = coeff[i][j]
                for k in range(28):
                    val = to_lean_real(c[k])
                    f.write(f"  {val},\n")
            f.write("]\n\n")
            f.write(f"def lieBracketCoeffRow{i} (j k : Fin 28) : ℝ :=\n")
            f.write("  rowData[j.val * 28 + k.val]!\n")
        print(f"Wrote {path}", file=sys.stderr)

    main_path = hqiv / "GeneratorsLieClosureData.lean"
    with open(main_path, "w") as f:
        for i in range(28):
            f.write(f"import Hqiv.GeneratorsLieClosureData{i}\n")
        f.write("\nnamespace Hqiv\n\n")
        f.write("/-- Coefficients for [so8Generator i, so8Generator j] = ∑ k, lieBracketCoeff i j k • so8Generator k. Chunked. -/\n")
        for i in range(28):
            f.write(f"private def row{i} (j k : Fin 28) : ℝ := lieBracketCoeffRow{i} j k\n")
        f.write("private def rows : Array (Fin 28 → Fin 28 → ℝ) := #[\n")
        f.write("  " + ", ".join(f"row{i}" for i in range(28)) + "\n")
        f.write("]\n\n")
        f.write("def lieBracketCoeff (i j : Fin 28) : Fin 28 → ℝ := fun k => rows[i.val]! j k\n\n")
        f.write("end Hqiv\n")
    print(f"Wrote {main_path}", file=sys.stderr)


def main(write_file: bool = False) -> None:
    import numpy as np
    from HQVM.matrices import OctonionHQIVAlgebra

    alg = OctonionHQIVAlgebra(verbose=False)
    basis = alg.lie_closure_basis(tol=1e-10)
    assert len(basis) == 28
    B = np.array([matrix_to_vec28(G) for G in basis]).T  # 28 x 28
    try:
        B_inv = np.linalg.inv(B)
    except np.linalg.LinAlgError:
        print("-- B is singular", file=sys.stderr)
        sys.exit(1)

    def bracket(i: int, j: int):
        return basis[i] @ basis[j] - basis[j] @ basis[i]

    coeff = []
    for i in range(28):
        row = []
        for j in range(28):
            if i == j:
                row.append([0.0] * 28)
            else:
                br = bracket(i, j)
                v = np.array(matrix_to_vec28(br))
                c = B_inv @ v
                row.append([float(c[k]) for k in range(28)])
        coeff.append(row)

    write_chunked = "--write-chunked" in sys.argv or "-c" in sys.argv
    if write_file:
        out_path = _REPO_LEAN / "Hqiv" / "GeneratorsLieClosureData.lean"
        write_lean_file(out_path, coeff)
        print(f"Wrote {out_path}", file=sys.stderr)
        return
    if write_chunked:
        write_lean_chunked(_REPO_LEAN, coeff)
        return

    print("-- Generated by scripts/print_lie_bracket_closure.py")
    print("-- Paste below into Hqiv/GeneratorsLieClosure.lean (after lieBracketCoeff_0_1)")
    print()
    print("/-- Coefficients for [so8Generator i, so8Generator j] = ∑ k, lieBracketCoeff i j k • so8Generator k -/")
    print("def lieBracketCoeff (i j : Fin 28) : Fin 28 → ℝ := fun k =>")
    print("  match i, j, k with")
    for i in range(28):
        for j in range(28):
            c = coeff[i][j]
            for k in range(28):
                val = to_lean_real(c[k])
                print(f"  | {i}, {j}, {k} => {val}")
    print("  end")
    print()
    i, j = 0, 1
    br = bracket(i, j)
    recomputed = sum(coeff[i][j][k] * basis[k] for k in range(28))
    err = np.max(np.abs(br - recomputed))
    print(f"-- Verification [0,1]: max |bracket - ∑ c_k gen_k| = {err}")
    if err > 1e-8:
        print("-- WARNING: residual large", file=sys.stderr)


if __name__ == "__main__":
    write_file = "--write" in sys.argv or "-w" in sys.argv
    main(write_file=write_file)
